# Generated by Django 5.2.8 on 2025-11-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('slocation', models.CharField(max_length=100)),
                ('semail', models.EmailField(max_length=100, unique=True)),
                ('sage', models.IntegerField()),
            ],
        ),
    ]
